# GitHub Sponsors (optional)
github: []

# Other funding platforms (optional)
patreon: 
ko_fi: 
open_collective: 
liberapay: 

# Custom funding links
custom:
  - "https://www.paypal.com/ncp/payment/NKZHVG2EE5TEQ"
